#!/bin/bash
#
# respaldo
# Command line interface to perform borg backups
# Carlos Escutia
# last modified: 17/03/22 dd/mm/yy
#

# Save file descriptors so they can be restored
exec 3>&1 4>&2

# get parameters from config file
# filename must be respaldo.config
# example config file:
#
#################################
## configure here your parameters
#
## where to store logs and mount backups
#workdir="/home/administrador/respaldos"
#
## backup parameters
#compression="lz4"
#
## borg server parameters
## borg user password not needed since 
## we're using ssh key based authentication
#backupuser="borgbackup"
#backupserver="172.31.100.109"
#backupport="22"
#backupdir="/home/borgbackup/"
#
## backup retention policy
#resp_dia=7
#resp_sem=4
#resp_mes=3
#
## end of config
#################################
#
currdir=`dirname "$0"`
source $currdir/respaldo.config

# example credentials file used by dump function
# filename should be credenciales.project
# 
# credentials for postgre database
#PG_HOST="localhost"
#PG_USER="user"
#PG_DB="db"
#
# credentials for mysql database
#MY_HOST="localhost"
#MY_DB="db"
#MY_PWD="pwd"
#

PROGNAME=${0##*/}
VERSION="0.3"

clean_up () { # Perform pre-exit housekeeping
    exec 2>&4 1>&3
    return
}

error_exit () {
    echo -e "${PROGNAME}: ${1:-"Unknown error"}" >&2
    clean_up
    exit 1
}

graceful_exit () {
    clean_up
    exit
}

signal_exit() { # Handle trapped signals
    case $1 in
        INT)
            error_exit "Program interrupted by user" 
            ;;
        TERM)
            echo -e "\n$PROGNAME: Program terminated" >&2
            graceful_exit 
            ;;
        *)
            error_exit "$PROGNAME: Terminating on unknown signal"
            ;;
    esac
}

usage () {
    echo -e "$PROGNAME [OPTION] [COMMAND]"
}

startlog () {
    exec > >(tee -a $logfile) 2>&1
}

endlog () {
    exec 2>&4 1>&3
}

# mensaje "Hola" will print: 16/08/2021 14:38:27 Hola
mensaje() {
    printf "%s %s\n" "$( date '+%d/%m/%Y %H:%M:%S' )" "$*" 
}

# initializes project repository in remote server
init () {
    mensaje "** Inicializando repositorio **"
    $BORG init -e repokey-blake2 ssh://$backupuser@$backupserver:$backupport/$backupdir/$project/
    status=$?
    if [ ${status} -eq 0 ] ; then
        mensaje "** Repositorio inicializado en servidor $backupserver listo para respaldar proyecto $project **"
    else
        mensaje "** Inicialización terminada con advertencia o error. Verifique el mensaje anterior. **"
    fi
}

# backs up project to remote server
backup () {
    mensaje "Iniciando respaldo de archivos del proyecto"
    cd $projectdir > /dev/null
    $BORG create --stats --compress $compression ssh://$backupuser@$backupserver:$backupport/$backupdir/$project/::`echo $project`_`date +%d-%m-%Y_%H-%M` ./ 
    status=$?
    if [ ${status} -eq 0 ] ; then
        mensaje "Respaldo de archivos terminado."
    else
        mensaje "Respaldo de archivos terminado con advertencia o error. Verifique el mensaje anterior."
    fi
}

# dumps database in backup/ directory so it can be backed up by borgbackup
dump () {
    mensaje "Iniciando volcado de base de datos"
    cd $projectdir > /dev/null
    if [ $postgres ] ; then
        if [ $dbcontainer ] ; then
            /usr/local/bin/docker-compose exec -T $dbcontainer sh -c 'pg_dump -U $POSTGRES_USER --format=c --file=/backup/db_$POSTGRES_DB\_`date +%d%b%y`.pgsql $POSTGRES_DB'
            status=$?
        else
            source $workdir/credenciales.$project
            pg_dump -h $PG_HOST -U $PG_USER --format=c --file=./backup/db_$PG_DB\_`date +%d%b%y`.pgsql $PG_DB
            status=$?
        fi
    fi
    if [ $mysql ] ; then
        if [ $dbcontainer ] ; then
            /usr/local/bin/docker-compose exec -T $dbcontainer sh -c 'mysqldump -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE --single-transaction --quick --lock-tables=false > /backup/db_$MYSQL_DATABASE\_`date +%d%b%y`.mysql'
            status=$?
        else
            source $workdir/credenciales.$project
            mysqldump -h$MY_HOST -uroot -p$MY_PWD $MY_DB --single-transaction --quick --lock-tables=false > ./backup/db_$MY_DB\_`date +%d%b%y`.mysql
            status=$?
        fi
    fi
    ls -lrth $projectdir/backup
    if [ ${status} -eq 0 ] ; then
        mensaje "Volcado de base de datos terminado."
    else
        mensaje "Volcado de base de datos terminado con advertencia o error. Verifique el mensaje anterior."
    fi
}

# clears database dumps
cleardbs () {
    mensaje "Iniciando eliminación de volcados de bases de datos"
    ls -lrth $projectdir/backup
    rm -f $projectdir/backup/*sql 
    status=$?
    ls -lrth $projectdir/backup
    if [ ${status} -eq 0 ] ; then
        mensaje "Eliminación de volcados de bases de datos terminado."
    else
        mensaje "Eliminación de volcados de bases de datos terminado con advertencia o error. Verifique el mensaje anterior."
    fi
}

# lists backups on remote server
list () {
    echo "Listado de respaldos:"
    $BORG list -v ssh://$backupuser@$backupserver:$backupport/$backupdir/$project/ 
}

# mounts remote backup to restore
mount () {
    if [[ ! -e $mountpoint ]]; then
        mkdir -p $mountpoint
    fi
    $BORG mount ssh://$backupuser@$backupserver:$backupport/$backupdir/$project/ $mountpoint
    status=$?
    if [ ${status} -eq 0 ] ; then
        mensaje "Respaldos accesibles en $mountpoint"
    else
        mensaje "Montado de respaldos terminado con advertencia o error. Verifique el mensaje anterior."
    fi
}

# unmounts remote backup
# replaced umount with fusermount to allow non-root user to umount in ubuntu 14.04
desmontar () {
    #umount $mountpoint
    fusermount -u $mountpoint
    status=$?
    if [ ${status} -eq 0 ] ; then
        mensaje "Respaldos desmontados de $mountpoint"
    else
        mensaje "Desmontado de respaldos terminado con advertencia o error. Verifique el mensaje anterior."
    fi
}


# shows information about the backup repository
info () {
    echo "Información del repositorio de respaldo:"
    $BORG info ssh://$backupuser@$backupserver:$backupport/$backupdir/$project/
}

# cleans old backups
prune () {
    mensaje "** Iniciando limpieza de repositorio **"
    $BORG prune --stats --progress --list --prefix $project\_ --show-rc --keep-daily $resp_dia --keep-weekly $resp_sem --keep-monthly $resp_mes ssh://$backupuser@$backupserver:$backupport/$backupdir/$project/ 
    status=$?
    if [ ${status} -eq 0 ] ; then
        mensaje "** Limpieza de repositorio terminada. **"
    else
        mensaje "** Limpieza de repositorio terminada con advertencia o error. Verifique el mensaje anterior. **"
    fi
}

help_message () {
        cat << EOF

$PROGNAME $VERSION
Command line interface to perform borg backups

Usage:
    $(usage)

Options:
    -h, --help ...................... Show this help and quit.
    -p, --project ................... Name of project. Required.
    -d, --projectdir ................ Directory of project. Required for backup and dump commands.
    -pg --postgres .................. Project has postgres database
    -my --mysql ..................... Project has mysql database
    -dbc --db_container ............. Name of database container

Available commands:
    init ............................ Initialize the backup repository
    backup .......................... Backup a project 
    dump ............................ Dumps database in backup/ directory
    list ............................ List existing backups
    mount ........................... Mount repository on filesystem to restore
    umount .......................... Unmount repository
    info ............................ Show statistics about backups
    prune ........................... Remove old backups 

EOF
exit 1
}

# Trap signals
trap "signal_exit TERM" TERM HUP
trap "signal_exit INT" INT

####### Main
missingfields=0

# Options
while [ -n "$1" ] ; do
    case $1 in
        -h | --help)
            help_message
            graceful_exit
            ;;
        -p | --project)
            shift
            project="$1"
            ;;
        -d | --projectdir)
            shift
            projectdir="$1"
            ;;
        -pg | --postgres)
            postgres=1
            ;;
        -my | --mysql)
            mysql=1
            ;;
        -dbc | --dbcontainer)
            shift
            dbcontainer="$1"
            ;;
        *)
            comando="$1"
            ;;
    esac
    shift
done

if [ -z $project ] ; then
    echo "Error: no se ha especificado el nombre del proyecto"
    missingfields=1
fi

if [ -z $projectdir ] && [[ $comando == @(backup|dump) ]] ; then
    echo "Error: no se ha especificado el directorio del proyecto"
    missingfields=1
fi

cd / > /dev/null
if [ ! -d $projectdir ] ; then
    echo "Error: No existe el directorio de proyecto especificado. Utilice ruta absoluta o ~/ruta ."
    missingfields=1
fi

if [ $postgres ] && [ $mysql ] && [[ $comando == @(backup|dump) ]] ; then
    echo "No se puede especificar más de una opción de base de datos"
    missingfields=1
fi

if [ -z $comando ] ; then
    echo "Error: no se ha especificado el comando a ejecutar"
    missingfields=1
fi

if [ $missingfields = 1 ] ; then
    help_message
    graceful_exit
fi

# Use $project parameter to define depending variables

# passphrase to gain access to backup
export BORG_PASSPHRASE=$project

# logs
logfile=$workdir/$project.log

# mountpoint for inspecting backups
mountpoint="$workdir/mnt/$project"

# Commands
case $comando in
    init)
        startlog
        init
        endlog
        ;;
    backup)
        startlog
        mensaje "** Respaldo de proyecto iniciado **"
        if grep -qs '$mountpoint ' /proc/mounts ; then
            desmontar
        fi
        if [ $postgres ] || [ $mysql ] ; then
            cleardbs
            dump
        fi
        backup
        if [ $postgres ] || [ $mysql ] ; then
            cleardbs
        fi
        mensaje "** Respaldo de proyecto terminado **"
        endlog
        ;;
    dump)
        dump
        ;;
    list)
        list
        ;;
    mount)
        mount
        ;;
    umount)
        desmontar
        ;;
    info)
        list
        echo
        info
        ;;
    prune)
        startlog
        if grep -qs'$mountpoint ' /proc/mounts ; then
            desmontar
        fi
        prune
        endlog
        ;;
    *)
        help_message
        graceful_exit
        ;;
esac
